# nameOverride: ""
# fullnameOverride: ""

kind: "DaemonSet"

serviceAccount:
  create: true

rbac:
  create: true

volumes:
- name: varlog
  hostPath:
    path: /var/log
- name: varlibdockercontainers
  hostPath:
    path: /var/lib/docker/containers
- name: etcfluentd-main
  configMap:
    name: fluentd-main
    defaultMode: 0777
- name: etcfluentd-config
  configMap:
    name: fluentd-config
    defaultMode: 0777

volumeMounts:
- name: varlog
  mountPath: /var/log
- name: varlibdockercontainers
  mountPath: /var/lib/docker/containers
  readOnly: true
- name: etcfluentd-main
  mountPath: /etc/fluent
- name: etcfluentd-config
  mountPath: /etc/fluent/config.d/


metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus-operator
    namespace: ""
    namespaceSelector: {}
    metricRelabelings: []
    relabelings: []

dashboards:
  enabled: "true"
  namespace: ""
  labels:
    grafana_dashboard: '"1"'

fileConfigs:
  01_sources.conf: |-
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      exclude_path ["/var/log/containers/*fluentd*.log"]
      pos_file /var/log/fluentd-containers.log.pos
      tag k8s.*
      read_from_head true
      <parse>
        @type json
        time_key @timestamp
        time_format %Y-%m-%dT%H:%M:%S.%N%z
        keep_time_key true
      </parse>
    </source>   

  02_filters.conf: |-
    <filter k8s.**>
      @type kubernetes_metadata
      skip_container_metadata "true"
    </filter>
  
      #log message is split when using fluentd logging driver(https://github.com/moby/moby/issues/34620)
    <filter k8s.**> 
      @id filter_concat
      @type concat
      key log
      use_first_timestamp true
      multiline_end_regexp /\n$/
      separator ""
    </filter>
  
    #Parsing logs into json fields and remove key name
    <filter k8s.**>
      @type parser
      @log_level info
      key_name log
      reserve_data true
      reserve_time true
      remove_key_name_field true
      emit_invalid_record_to_error false
      replace_invalid_sequence true 
      <parse>
        @type json
      </parse>
    </filter>
  
    <filter k8s.**>
      @type record_transformer
      enable_ruby true
      <record>
        log_json ${record["log"]}
      </record>
      remove_keys $.kubernetes.labels.rollouts-pod-template-hash,$.kubernetes.pod_id,$.kubernetes.container_image
    </filter> 
  03_dispatch.conf: |-
    ##

  04_outputs.conf: |-
    <match **>
      @type file
      path /tmp/testlog
    </match>  