daemonset:
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
          - "/var/log/containers/*.log"
        exclude_files:
          - "/var/log/containers/hello-node-deployment-*.log"
          - "/var/log/containers/hn-ms*.log"
          - "/var/log/containers/filebeat*.log"
          - "/var/log/containers/logstash*.log"
        fields:
          logStram__________Type: full_log

      - type: container
        paths:
          - "/var/log/containers/hello-node-deployment-*.log"
          - "/var/log/containers/hn-ms*.log"
        fields:
          logStram__________Type: application_log

        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
                

      output.logstash:
        hosts: ["elk-logstash-logstash:5044"]
      # output.console:
      #   pretty: true
      #   enabled: true      